In [1]:
import pandas as pd

In [7]:
unames =['user_id', 'gender','age','occupation','zip']

In [8]:
users=pd.read_table('G:/learn/JupyterCode/pydata-book/ch02/movielens/users.dat',sep='::',header=None,names=unames)

E:\ruanjian\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':

In [9]:
print(len(users))
users.head()

6040

   user_id gender  age  occupation    zip
0        1      F    1          10  48067
1        2      M   56          16  70072
2        3      M   25          15  55117
3        4      M   45           7  02460
4        5      M   25          20  55455

In [10]:
import matplotlib.pyplot as plt
import numpy as np

In [15]:
rnames=['user_id','movie_id','rating','timestamp']
ratings=pd.read_table('G:/learn/JupyterCode/pydata-book/ch02/movielens/ratings.dat',\
                      sep='::',header=None,names=rnames)

E:\ruanjian\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app

In [16]:
mnames=['movie_id','title','genres']
movies=pd.read_table('G:/learn/JupyterCode/pydata-book/ch02/movielens/movies.dat',\
                      sep='::',header=None,names=mnames)

E:\ruanjian\Anaconda2\envs\gl-env\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators; you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app

In [17]:
ratings[:5]

   user_id  movie_id  rating  timestamp
0        1      1193       5  978300760
1        1       661       3  978302109
2        1       914       3  978301968
3        1      3408       4  978300275
4        1      2355       5  978824291

In [18]:
movies[:5]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

In [19]:
ratings

         user_id  movie_id  rating  timestamp
0              1      1193       5  978300760
1              1       661       3  978302109
2              1       914       3  978301968
3              1      3408       4  978300275
4              1      2355       5  978824291
5              1      1197       3  978302268
6              1      1287       5  978302039
7              1      2804       5  978300719
8              1       594       4  978302268
9              1       919       4  978301368
10             1       595       5  978824268
11             1       938       4  978301752
12             1      2398       4  978302281
13             1      2918       4  978302124
14             1      1035       5  978301753
15             1      2791       4  978302188
16             1      2687       3  978824268
17             1      2018       4  978301777
18             1      3105       5  978301713
19             1      2797       4  978302039
20             1      2321       3  978302205
21             1       720       3  978300760
22             1      1270       5  978300055
23             1       527       5  978824195
24             1      2340       3  978300103
25             1        48       5  978824351
26             1      1097       4  978301953
27             1      1721       4  978300055
28             1      1545       4  978824139
29             1       745       3  978824268
...          ...       ...     ...        ...
1000179     6040      2762       4  956704584
1000180     6040      1036       3  956715455
1000181     6040       508       4  956704972
1000182     6040      1041       4  957717678
1000183     6040      3735       4  960971654
1000184     6040      2791       4  956715569
1000185     6040      2794       1  956716438
1000186     6040       527       5  956704219
1000187     6040      2003       1  956716294
1000188     6040       535       4  964828734
1000189     6040      2010       5  957716795
1000190     6040      2011       4  956716113
1000191     6040      3751       4  964828782
1000192     6040      2019       5  956703977
1000193     6040       541       4  956715288
1000194     6040      1077       5  964828799
1000195     6040      1079       2  956715648
1000196     6040       549       4  956704746
1000197     6040      2020       3  956715288
1000198     6040      2021       3  956716374
1000199     6040      2022       5  956716207
1000200     6040      2028       5  956704519
1000201     6040      1080       4  957717322
1000202     6040      1089       4  956704996
1000203     6040      1090       3  956715518
1000204     6040      1091       1  956716541
1000205     6040      1094       5  956704887
1000206     6040       562       5  956704746
1000207     6040      1096       4  956715648
1000208     6040      1097       4  956715569

[1000209 rows x 4 columns]

In [20]:
data=pd.merge(pd.merge(ratings,users),movies) #合并数据

In [21]:
data

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,1193,5,978298413,M,56,16,70072,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,1193,4,978220179,M,25,12,32793,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,1193,4,978199279,M,25,7,22903,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,1193,5,978158471,M,50,1,95350,One Flew Over the Cuckoo's Nest (1975),Drama
5,18,1193,4,978156168,F,18,3,95825,One Flew Over the Cuckoo's Nest (1975),Drama
6,19,1193,5,982730936,M,1,10,48073,One Flew Over the Cuckoo's Nest (1975),Drama
7,24,1193,5,978136709,F,25,7,10023,One Flew Over the Cuckoo's Nest (1975),Drama
8,28,1193,3,978125194,F,25,1,14607,One Flew Over the Cuckoo's Nest (1975),Drama
9,33,1193,5,978557765,M,45,3,55421,One Flew Over the Cuckoo's Nest (1975),Drama
10,39,1193,5,978043535,M,18,4,61820,One Flew Over the Cuckoo's Nest (1975),Drama
11,42,1193,3,978038981,M,25,8,24502,One Flew Over the Cuckoo's Nest (1975),Drama
12,44,1193,4,978018995,M,45,17,98052,One Flew Over the Cuckoo's Nest (1975),Drama
13,47,1193,4,977978345,M,18,4,94305,One Flew Over the Cuckoo's Nest (1975),Drama
14,48,1193,4,977975061,M,25,4,92107,One Flew Over the Cuckoo's Nest (1975),Drama
15,49,1193,4,978813972,M,18,12,77084,One Flew Over the Cuckoo's Nest (1975),Drama
16,53,1193,5,977946400,M,25,0,96931,One Flew Over the Cuckoo's Nest (1975),Drama
17,54,1193,5,977944039,M,50,1,56723,One Flew Over the Cuckoo's Nest (1975),Drama
18,58,1193,5,977933866,M,25,2,30303,One Flew Over the Cuckoo's Nest (1975),Drama
19,59,1193,4,977934292,F,50,1,55413,One Flew Over the Cuckoo's Nest (1975),Drama
20,62,1193,4,977968584,F,35,3,98105,One Flew Over the Cuckoo's Nest (1975),Drama
21,80,1193,4,977786172,M,56,1,49327,One Flew Over the Cuckoo's Nest (1975),Drama
22,81,1193,5,977785864,F,25,0,60640,One Flew Over the Cuckoo's Nest (1975),Drama
23,88,1193,5,977694161,F,45,1,02476,One Flew Over the Cuckoo's Nest (1975),Drama
24,89,1193,5,977683596,F,56,9,85749,One Flew Over the Cuckoo's Nest (1975),Drama
25,95,1193,5,977626632,M,45,0,98201,One Flew Over the Cuckoo's Nest (1975),Drama
26,96,1193,3,977621789,F,25,16,78028,One Flew Over the Cuckoo's Nest (1975),Drama
27,99,1193,2,982791053,F,1,10,19390,One Flew Over the Cuckoo's Nest (1975),Drama
28,102,1193,5,1040737607,M,35,19,20871,One Flew Over the Cuckoo's Nest (1975),Drama
29,104,1193,2,977546620,M,25,12,00926,One Flew Over the Cuckoo's Nest (1975),Drama
...,...,...,...,...,...,...,...,...,...,...
1000179,4933,3084,3,962757020,M,25,15,94040,Home Page (1999),Documentary
1000180,4802,2218,2,1014866656,M,56,1,40601,Juno and Paycock (1930),Drama
1000181,4812,2308,2,962932391,M,18,14,25301,Detroit 9000 (1973),Action|Crime
1000182,4874,624,4,962781918,F,25,4,70808,Condition Red (1995),Action|Drama|Thriller
1000183,5059,1434,4,962484364,M,45,16,22652,"Stranger, The (1994)",Action
1000184,5947,1434,4,957190428,F,45,16,97215,"Stranger, The (1994)",Action
1000185,5077,1868,3,962417299,M,25,2,20037,"Truce, The (1996)",Drama|War
1000186,5944,1868,1,957197520,F,18,10,27606,"Truce, The (1996)",Drama|War
1000187,5105,404,3,962337582,M,50,7,18977,Brother Minister: The Assassination of Malcolm...,Documentary
1000188,5185,404,4,963402617,F,35,4,44485,Brother Minister: The Assassination of Malcolm...,Documentary
1000189,5532,404,5,959619841,M,25,17,27408,Brother Minister: The Assassination of Malcolm...,Documentary
1000190,5543,404,3,960127592,M,25,17,97401,Brother Minister: The Assassination of Malcolm...,Documentary
1000191,5220,2543,3,961546137,M,25,7,91436,Six Ways to Sunday (1997),Comedy
1000192,5754,2543,4,958272316,F,18,1,60640,Six Ways to Sunday (1997),Comedy
1000193,5227,591,3,961475931,M,18,10,64050,Tough and Deadly (1995),Action|Drama|Thriller
1000194,5795,591,1,958145253,M,25,1,92688,Tough and Deadly (1995),Action|Drama|Thriller
1000195,5313,3656,5,960920392,M,56,0,55406,Lured (1947),Crime
1000196,5328,2438,4,960838075,F,25,4,91740,Outside Ozona (1998),Drama|Thriller
1000197,5334,3323,3,960796159,F,56,13,46140,Chain of Fools (2000),Comedy|Crime
1000198,5334,127,1,960795494,F,56,13,46140,"Silence of the Palace, The (Saimt el Qusur) (1...",Drama
1000199,5334,3382,5,960796159,F,56,13,46140,Song of Freedom (1936),Drama
1000200,5420,1843,3,960156505,F,1,19,14850,Slappy and the Stinkers (1998),Children's|Comedy
1000201,5433,286,3,960240881,F,35,17,45014,Nemesis 2: Nebula (1995),Action|Sci-Fi|Thriller
1000202,5494,3530,4,959816296,F,35,17,94306,Smoking/No Smoking (1993),Comedy
1000203,5556,2198,3,959445515,M,45,6,92103,Modulations (1998),Documentary
1000204,5949,2198,5,958846401,M,18,17,47901,Modulations (1998),Documentary
1000205,5675,2703,3,976029116,M,35,14,30030,Broken Vessels (1998),Drama
1000206,5780,2845,1,958153068,M,18,17,92886,White Boys (1999),Drama
1000207,5851,3607,5,957756608,F,18,20,55410,One Little Indian (1973),Comedy|Drama|Western
1000208,5938,2909,4,957273353,M,25,1,35401,"Five Wives, Three Secretaries and Me (1998)",Documentary

In [22]:
data.ix[0]

user_id                                            1
movie_id                                        1193
rating                                             5
timestamp                                  978300760
gender                                             F
age                                                1
occupation                                        10
zip                                            48067
title         One Flew Over the Cuckoo's Nest (1975)
genres                                         Drama
Name: 0, dtype: object

In [23]:
data[data.user_id==1]

,user_id,movie_id,rating,timestamp,gender,age,occupation,zip,title,genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1725,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2250,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
2886,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4201,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy
5904,1,1197,3,978302268,F,1,10,48067,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance
8222,1,1287,5,978302039,F,1,10,48067,Ben-Hur (1959),Action|Adventure|Drama
8926,1,2804,5,978300719,F,1,10,48067,"Christmas Story, A (1983)",Comedy|Drama
10278,1,594,4,978302268,F,1,10,48067,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical
11041,1,919,4,978301368,F,1,10,48067,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical
12759,1,595,5,978824268,F,1,10,48067,Beauty and the Beast (1991),Animation|Children's|Musical
13819,1,938,4,978301752,F,1,10,48067,Gigi (1958),Musical
14006,1,2398,4,978302281,F,1,10,48067,Miracle on 34th Street (1947),Drama
14386,1,2918,4,978302124,F,1,10,48067,Ferris Bueller's Day Off (1986),Comedy
15859,1,1035,5,978301753,F,1,10,48067,"Sound of Music, The (1965)",Musical
16741,1,2791,4,978302188,F,1,10,48067,Airplane! (1980),Comedy
18472,1,2687,3,978824268,F,1,10,48067,Tarzan (1999),Animation|Children's
18914,1,2018,4,978301777,F,1,10,48067,Bambi (1942),Animation|Children's
19503,1,3105,5,978301713,F,1,10,48067,Awakenings (1990),Drama
20183,1,2797,4,978302039,F,1,10,48067,Big (1988),Comedy|Fantasy
21674,1,2321,3,978302205,F,1,10,48067,Pleasantville (1998),Comedy
22832,1,720,3,978300760,F,1,10,48067,Wallace & Gromit: The Best of Aardman Animatio...,Animation
23270,1,1270,5,978300055,F,1,10,48067,Back to the Future (1985),Comedy|Sci-Fi
25853,1,527,5,978824195,F,1,10,48067,Schindler's List (1993),Drama|War
28157,1,2340,3,978300103,F,1,10,48067,Meet Joe Black (1998),Romance
28501,1,48,5,978824351,F,1,10,48067,Pocahontas (1995),Animation|Children's|Musical|Romance
28883,1,1097,4,978301953,F,1,10,48067,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi
31152,1,1721,4,978300055,F,1,10,48067,Titanic (1997),Drama|Romance
32698,1,1545,4,978824139,F,1,10,48067,Ponette (1996),Drama
32771,1,745,3,978824268,F,1,10,48067,"Close Shave, A (1995)",Animation|Comedy|Thriller
33428,1,2294,4,978824291,F,1,10,48067,Antz (1998),Animation|Children's
34073,1,3186,4,978300019,F,1,10,48067,"Girl, Interrupted (1999)",Drama
34504,1,1566,4,978824330,F,1,10,48067,Hercules (1997),Adventure|Animation|Children's|Comedy|Musical
34973,1,588,4,978824268,F,1,10,48067,Aladdin (1992),Animation|Children's|Comedy|Musical
36324,1,1907,4,978824330,F,1,10,48067,Mulan (1998),Animation|Children's
36814,1,783,4,978824291,F,1,10,48067,"Hunchback of Notre Dame, The (1996)",Animation|Children's|Musical
37204,1,1836,5,978300172,F,1,10,48067,"Last Days of Disco, The (1998)",Drama
37339,1,1022,5,978300055,F,1,10,48067,Cinderella (1950),Animation|Children's|Musical
37916,1,2762,4,978302091,F,1,10,48067,"Sixth Sense, The (1999)",Thriller
40375,1,150,5,978301777,F,1,10,48067,Apollo 13 (1995),Drama
41626,1,1,5,978824268,F,1,10,48067,Toy Story (1995),Animation|Children's|Comedy
43703,1,1961,5,978301590,F,1,10,48067,Rain Man (1988),Drama
45033,1,1962,4,978301753,F,1,10,48067,Driving Miss Daisy (1989),Drama
45685,1,2692,4,978301570,F,1,10,48067,Run Lola Run (Lola rennt) (1998),Action|Crime|Romance
46757,1,260,4,978300760,F,1,10,48067,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi
49748,1,1028,5,978301777,F,1,10,48067,Mary Poppins (1964),Children's|Comedy|Musical
50759,1,1029,5,978302205,F,1,10,48067,Dumbo (1941),Animation|Children's|Musical
51327,1,1207,4,978300719,F,1,10,48067,To Kill a Mockingbird (1962),Drama
52255,1,2028,5,978301619,F,1,10,48067,Saving Private Ryan (1998),Action|Drama|War
54908,1,531,4,978302149,F,1,10,48067,"Secret Garden, The (1993)",Children's|Drama
55246,1,3114,4,978302174,F,1,10,48067,Toy Story 2 (1999),Animation|Children's|Comedy
56831,1,608,4,978301398,F,1,10,48067,Fargo (1996),Crime|Drama|Thriller
59344,1,1246,4,978302091,F,1,10,48067,Dead Poets Society (1989),Drama

按性别计算不同电影的平均分

In [27]:
mean_ratings=data.pivot_table(values='rating',index='title',columns='gender',aggfunc='mean')
mean_ratings.head(10)

gender                                    F         M
title
$1,000,000 Duck (1971)             3.375000  2.761905
'Night Mother (1986)               3.388889  3.352941
'Til There Was You (1997)          2.675676  2.733333
'burbs, The (1989)                 2.793478  2.962085
...And Justice for All (1979)      3.828571  3.689024
1-900 (1994)                       2.000000  3.000000
10 Things I Hate About You (1999)  3.646552  3.311966
101 Dalmatians (1961)              3.791444  3.500000
101 Dalmatians (1996)              3.240000  2.911215
12 Angry Men (1957)                4.184397  4.328421